/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LambdaApiGatewayProj;

import java.util.HashSet;

public class RepeatedWord {
    public static String repeatedWord(String longStringOfWords) {
        String words[] = longStringOfWords.split(" ");
        String tmpWord = "";
        HashSet<String> bagOfWords = new HashSet<>();

        for (String word: words) {
            // Regex taken from:
            // https://stackoverflow.com/questions/12506655/how-can-i-remove-all-leading-and-trailing-punctuation
            tmpWord = word.toLowerCase().replaceAll("[^a-zA-Z]+$", "");
            if (bagOfWords.contains(tmpWord))
                return tmpWord;
            else
                bagOfWords.add(tmpWord);
        }
        return null;
    }
}