/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LambdaApiGatewayProj;

import org.junit.Test;
import static org.junit.Assert.*;

public class RepeatedWordTest {
    @Test public void testSomeTest() {
    }
}
